version: 2.1

executors:
  docker-circleci:
    working_directory: "~/repo"
    docker:
      - image: "circleci/node:10.12-stretch-browsers"

jobs:
  unit_test:
    executor: docker-circleci
    steps:
      - checkout
      - run: npm ci
      - run: npm test
  prepare_release:
    executor: docker-circleci
    steps:
      - checkout
      - run: npm ci
      - run: npm build

workflows:
  build_test:
    jobs:
      - unit_test
      - prepare_release
